# SPDX-License-Identifier: GPL-3.0-only
# Read-only observation of the pinned resolver's consumed set. No acquisition,
# configuration changes or global all-platform source prefetch is performed.
function(_waveweft_json_string value output)
    string(REPLACE "\\" "\\\\" value "${value}")
    string(REPLACE "\"" "\\\"" value "${value}")
    string(REPLACE "\n" "\\n" value "${value}")
    string(REPLACE "\r" "\\r" value "${value}")
    string(REPLACE "\t" "\\t" value "${value}")
    set(${output} "\"${value}\"" PARENT_SCOPE)
endfunction()

function(_waveweft_dependency_record name output)
    if(NOT name MATCHES "^[a-z0-9_-]+$")
        message(FATAL_ERROR "Invalid consumed dependency name: ${name}")
    endif()
    set(recipe "muse_deps/recipes/${name}")
    if(name STREQUAL "portaudio")
        set(recipe "distribution/recipes/portaudio")
    endif()
    # Includes run in this isolated function scope and cannot leak DEP_* values.
    get_cmake_property(variables VARIABLES)
    foreach(variable IN LISTS variables)
        if(variable MATCHES "^DEP_")
            set(${variable} "")
        endif()
    endforeach()
    include("${PROJECT_SOURCE_DIR}/${recipe}/spec.cmake")
    get_property(prefix GLOBAL PROPERTY ${name}_PREFIX)
    get_property(source_root GLOBAL PROPERTY ${name}_SOURCE_DIR)
    get_property(runtime GLOBAL PROPERTY ${name}_INSTALL_LIBRARIES)
    if(NOT prefix OR NOT DEP_VERSION)
        message(FATAL_ERROR "Consumed dependency lacks prefix/version: ${name}")
    endif()
    set(record "{}")
    foreach(field IN ITEMS name recipe prefix source_root)
        _waveweft_json_string("${${field}}" value)
        string(JSON record SET "${record}" "${field}" "${value}")
    endforeach()
    _waveweft_json_string("${DEP_VERSION}" value)
    string(JSON record SET "${record}" version "${value}")
    if(DEP_SOURCE_URL)
        set(DEP_SOURCES "${name}|tarball|${DEP_SOURCE_URL}|${DEP_SOURCE_SHA256}")
    endif()
    foreach(field IN ITEMS sources runtime)
        set(values "${runtime}")
        if(field STREQUAL "sources")
            set(values "${DEP_SOURCES}")
        endif()
        set(array "[]")
        set(index 0)
        foreach(item IN LISTS values)
            _waveweft_json_string("${item}" value)
            string(JSON array SET "${array}" ${index} "${value}")
            math(EXPR index "${index} + 1")
        endforeach()
        string(JSON record SET "${record}" "${field}" "${array}")
    endforeach()
    set(${output} "${record}" PARENT_SCOPE)
endfunction()

function(waveweft_record_consumed_dependencies)
    get_property(consumed GLOBAL PROPERTY EXTDEPS_CONSUMED)
    if(NOT consumed)
        message(FATAL_ERROR "No consumed dependencies recorded")
    endif()
    list(REMOVE_DUPLICATES consumed)
    list(SORT consumed)
    set(records "[]")
    set(index 0)
    foreach(name IN LISTS consumed)
        _waveweft_dependency_record("${name}" record)
        string(JSON records SET "${records}" ${index} "${record}")
        math(EXPR index "${index} + 1")
    endforeach()
    set(result "{\"schemaVersion\":1}")
    string(JSON result SET "${result}" dependencies "${records}")
    file(WRITE "${PROJECT_BINARY_DIR}/waveweft-consumed-dependencies.json" "${result}\n")
endfunction()
