# SPDX-License-Identifier: GPL-3.0-only
# Observe the actual InstallRequiredSystemLibraries result; never replace it.
include("${PROJECT_SOURCE_DIR}/distribution/RecordConsumedDependencies.cmake")

function(waveweft_record_windows_runtimes)
    set(record "{\"schemaVersion\":1}")
    set(msvcRedistDir "${MSVC_REDIST_DIR}")
    set(msvcCrtDir "${MSVC_CRT_DIR}")
    set(vcInstallDir "$ENV{VCINSTALLDIR}")
    set(windowsSdkDir "$ENV{WindowsSdkDir}")
    set(windowsSdkVersion "$ENV{WindowsSDKVersion}")
    foreach(field IN ITEMS msvcRedistDir msvcCrtDir vcInstallDir windowsSdkDir windowsSdkVersion)
        _waveweft_json_string("${${field}}" value)
        string(JSON record SET "${record}" "${field}" "${value}")
    endforeach()
    set(debugRuntimes false)
    if(CMAKE_INSTALL_DEBUG_LIBRARIES OR CMAKE_INSTALL_DEBUG_LIBRARIES_ONLY)
        set(debugRuntimes true)
    endif()
    string(JSON record SET "${record}" debugRuntimes ${debugRuntimes})
    set(libraries "[]")
    set(index 0)
    foreach(path IN LISTS CMAKE_INSTALL_SYSTEM_RUNTIME_LIBS)
        _waveweft_json_string("${path}" value)
        string(JSON libraries SET "${libraries}" ${index} "${value}")
        math(EXPR index "${index}+1")
    endforeach()
    string(JSON record SET "${record}" libraries "${libraries}")
    file(WRITE "${PROJECT_BINARY_DIR}/waveweft-windows-runtimes.json" "${record}\n")
endfunction()
